---
- hosts: all

  tasks:
    - import_tasks: tasks/configure-hardware.yml
    - import_tasks: tasks/apt-init.yml
    - import_tasks: tasks/install-docker.yml
    - import_tasks: tasks/build-docker-images.yml
    - import_tasks: tasks/detect-hardware.yml
    - import_tasks: tasks/install-portainer.yml
    - import_tasks: tasks/configure-portainer.yml
    - import_tasks: tasks/configure-grafana.yml
