#!/usr/bin/env ansible-playbook

- name: Setup DFLD Messstation ZWO on Raspberry Pi
  hosts: messstation
  gather_facts: true
  become: true

  roles:
    - role: configure-raspi
    - role: geerlingguy.docker
      vars:
        docker_users:
          - "{{ dfld_user }}"
      when: ansible_facts.architecture == 'x86_64'
    - role: geerlingguy.docker_arm
      vars:
        docker_users:
          - "{{ dfld_user }}"
      when: ansible_facts.architecture == 'aarch64'
    - role: configure-raspi
    - role: build-images
    - role: portainer
    - role: detect_hardware
    - role: deploy_infrastructure_stack
    - role: configure-grafana
    - role: deploy_ingress_stack
      when: ansible_facts.architecture == 'aarch64'
  

  post_tasks:
    - name: Ready message
      debug:
        msg: 
          - ''
          - '------------------------------------------------------------------------------------------------------'
          - 'DFLD Messstation ZWO is ready.'
          - 'You can access the portainer services at: https://{{ ansible_host }}:9443 / User: {{ portainer_user }} Password:{{ portainer_password }}'
          - 'You can access the grafana services at: https://{{ ansible_host }}:3000 / User: {{ grafana_user }} Password:{{ grafana_password }}'
          - 'You can access the influxdb services at: https://{{ ansible_host }}:8086 / User: {{ influxdb_user }} Password:{{ influxdb_password }}'
          - 'Happy measuring!'
          - '------------------------------------------------------------------------------------------------------'
          - ''

    - name: Check if reboot is required
      when: check_reboot.stat.exists
      block:
        - name: Wait to ready
          ansible.builtin.pause:
            minutes: 1
            prompt: "Waiting for the system to reboot. You may copy the above messages for later use."

        - name: Reboot System
          ansible.builtin.reboot:
            msg: |
              Reboot is required.
              Your System will reboot now.
            reboot_timeout: 120
