---
- name: Run hardware detection in docker container
  shell: docker run --rm --privileged dfld_box python detect_hw.py
  register: detect_hw_response

- name: Extract hardware config to json fact
  set_fact:
    hw_conf: "{{ detect_hw_response.stdout|from_json }}"
    
- name: Print hardware setup
  debug:
    msg: "{{ hw_conf }}"

  