---
- name: Create a directory for portainer and all DFLD data
  become: yes
  ansible.builtin.file:
    path: /dfld/portainer_data
    state: directory
    recurse: yes
    owner: "root"
    group: "root"
    mode: 0700

- name: Installing Portainer
  docker_container:
    name: portainer
    image: portainer/portainer-ce:lts
    state: started
    restart_policy: "always"
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dfld/portainer_data:/data
    env:
      logo: "https://www.dfld.de/Basics/images/Logo-DFLD.svg"

- name: Check if admin account exists in Portainer 
  uri:
    url: "https://localhost:9443/api/users/admin/check"
    method: GET
    validate_certs: no
    status_code:
      - 200
      - 204
      - 404
  register: portainer_admin_user

- name: Create admin account in Portainer 
  uri:
    url: "https://localhost:9443/api/users/admin/init"
    method: POST
    body_format: json
    validate_certs: no
    headers:
      Content-Type: "application/json"
    body: '{"Username": "{{ ansible_env.USER }}", "Password": "{{ ansible_env.USER }}{{ ansible_env.USER }}{{ ansible_env.USER }}", "Role": 1}'
    status_code: 200
  when: portainer_admin_user.status != 204

  
