---

- name: Update and upgrade apt packages
  become: true
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 86400 # one day

- name: Install required packages
  become: true
  ansible.builtin.apt:
    pkg:
      - python3
      - python3-psycopg2
      - netcat-openbsd
    state: present

- name: Check if reboot is needed
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: check_reboot
