---

- name: Copy files for docker images
  ansible.builtin.copy:
    src: "{{ item }}/"
    dest: "{{ dfld_dir }}/{{ item }}"
    owner: "{{ dfld_user }}"
    group: "{{ dfld_group }}"
    mode: '0644'
    force: false
  loop: "{{ docker_images }}"

- name: Build dfld images
  community.docker.docker_image:
    name: "{{ item }}"
    build:
      path: "{{ dfld_dir }}/{{ item }}"
    source: build
  loop: "{{ docker_images }}"
