services:
  dump1090:
    image: jraviles/dump1090
    restart: unless-stopped
    container_name: dump1090
    networks:
      - network
    ports:
      - 8080:8080/tcp
      - 30003:30003/tcp
    devices:
      - /dev/bus/usb

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    container_name: postgres
    networks:
      - network
    ports:
      - 5432:5432
    volumes:
       - ${DOCKER_EXTERNAL_ROOT}/postgres/data:/data/postgres
    environment:
      POSTGRES_USER: ${ADMIN_USERNAME}
      POSTGRES_PASSWORD: ${ADMIN_PASSWORD}
      PGDATA: /data/postgres

  influxdb:
    image: influxdb:1.11.8-alpine
    restart: unless-stopped
    container_name: influxdb
    networks:
      - network
    ports:
      - 8086:8086
      - 8088:8088
    volumes:
      - ${DOCKER_EXTERNAL_ROOT}/influxdb/data:/var/lib/influxdb
      - ${DOCKER_EXTERNAL_ROOT}/influxdb/config:/etc/influxdb
    environment:
      - INFLUXDB_DB=${INFLUXDB_DATABASE}
      - INFLUXDB_ADMIN_USER=${ADMIN_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${ADMIN_PASSWORD}

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - GF_SECURITY_ADMIN_USER=${ADMIN_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
    user: ${UID}:${GID}
    ports:
      - 3000:3000
    networks:
      - network
    volumes:
      - ${DOCKER_EXTERNAL_ROOT}/grafana/data:/var/lib/grafana
      - ${DOCKER_EXTERNAL_ROOT}/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - INFLUXDB_DB=${INFLUX_TELEGRAF_DATABASE}
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USER=${ADMIN_USERNAME}
      - INFLUXDB_USER_PASSWORD=${ADMIN_PASSWORD}
    user: ${UID}:${GID}
    ports:
      - 8125:8125
      - 8092:8092
      - 8094:8094
    networks:
      - network
    volumes:
      - ${DOCKER_EXTERNAL_ROOT}/telegraf:/etc/telegraf
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb



networks:
    network:
        name: dfld_network
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "false"
        ipam:
            driver: default
            config:
                - subnet: 172.21.0.0/24
                  gateway: 172.21.0.1